org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.10
loader_version=0.16.10
fabric_version=0.141.1+1.21.11
yarn_mappings=1.21.11+build.4

# Mod Properties
mod_version=1.0.0
maven_group=chat.text.select
archives_base_name=chattextselect
